# Create image based on the official Node 8.x image from dockerhub
FROM node:carbon

# Create a directory where our app will be placed
RUN mkdir -p /usr/src/app

# Change directory so that our commands run inside this new directory
WORKDIR /usr/src/app

# Copy dependency definitions
COPY nodeApiFinal/nodeapi/package.json /usr/src/app

# Install dependencies
RUN npm install -g nodemon
#RUN npm install -g express-validator
RUN npm install

# Get all the code needed to run the app
#COPY nodeApiFinal/nodeapi/. /usr/src/app

# Expose the port the app runs in
EXPOSE 3000

# Serve the app
#CMD ["npm", "run start-dev"]
ENTRYPOINT npm run start-dev