# Create image based on the official Node 8.x image from dockerhub
FROM node:carbon

# Create a directory where our app will be placed
RUN mkdir -p /usr/src/app

# Change directory so that our commands run inside this new directory
WORKDIR /usr/src/app

# Copy dependency definitions
COPY angularStoreFinal/package.json /usr/src/app

# Install dependencies
RUN npm install -g --unsafe @angular/cli
RUN npm install

# Get all the code needed to run the app
#COPY angularStoreFinal/. /usr/src/app

# Expose the port the app runs in
EXPOSE 4200

# Serve the app
CMD ["npm", "start"]